// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using Newtonsoft.Json.Linq;

namespace AmbientSpeech.Models
{
    public partial class SASKeyRegistration
    {
        private string _eventHub;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string EventHub
        {
            get { return this._eventHub; }
            set { this._eventHub = value; }
        }
        
        private string _keyName;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string KeyName
        {
            get { return this._keyName; }
            set { this._keyName = value; }
        }
        
        private string _keyValue;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string KeyValue
        {
            get { return this._keyValue; }
            set { this._keyValue = value; }
        }
        
        private string _serviceNamespace;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string ServiceNamespace
        {
            get { return this._serviceNamespace; }
            set { this._serviceNamespace = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the SASKeyRegistration class.
        /// </summary>
        public SASKeyRegistration()
        {
        }
        
        /// <summary>
        /// Serialize the object
        /// </summary>
        /// <returns>
        /// Returns the json model for the type SASKeyRegistration
        /// </returns>
        public virtual JToken SerializeJson(JToken outputObject)
        {
            if (outputObject == null)
            {
                outputObject = new JObject();
            }
            if (this.EventHub != null)
            {
                outputObject["EventHub"] = this.EventHub;
            }
            if (this.KeyName != null)
            {
                outputObject["KeyName"] = this.KeyName;
            }
            if (this.KeyValue != null)
            {
                outputObject["KeyValue"] = this.KeyValue;
            }
            if (this.ServiceNamespace != null)
            {
                outputObject["ServiceNamespace"] = this.ServiceNamespace;
            }
            return outputObject;
        }
    }
}
