// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using AmbientSpeech.Models;
using Microsoft.Rest;

namespace AmbientSpeech
{
    public partial interface ISasKeys
    {
        /// <param name='serviceNamespace'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        Task<HttpOperationResponse<string>> GetEventHubsByNamespaceWithOperationResponseAsync(string serviceNamespace, CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        
        /// <param name='serviceNamespace'>
        /// Required.
        /// </param>
        /// <param name='eventHub'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        Task<HttpOperationResponse<string>> GetKeyNamesWithOperationResponseAsync(string serviceNamespace, string eventHub, CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        Task<HttpOperationResponse<string>> GetRegisteredNamespacesWithOperationResponseAsync(CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        
        /// <param name='keyRegistration'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        Task<HttpOperationResponse<string>> PostWithOperationResponseAsync(SASKeyRegistration keyRegistration, CancellationToken cancellationToken = default(System.Threading.CancellationToken));
    }
}
