// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Threading;
using System.Threading.Tasks;
using AmbientSpeech;
using Microsoft.Rest;
using Newtonsoft.Json.Linq;

namespace AmbientSpeech
{
    internal partial class SasToken : IServiceOperations<SASTokenAPI>, ISasToken
    {
        /// <summary>
        /// Initializes a new instance of the SasToken class.
        /// </summary>
        /// <param name='client'>
        /// Reference to the service client.
        /// </param>
        internal SasToken(SASTokenAPI client)
        {
            this._client = client;
        }
        
        private SASTokenAPI _client;
        
        /// <summary>
        /// Gets a reference to the AmbientSpeech.SASTokenAPI.
        /// </summary>
        public SASTokenAPI Client
        {
            get { return this._client; }
        }
        
        /// <param name='serviceNamespace'>
        /// Required.
        /// </param>
        /// <param name='eventHub'>
        /// Required.
        /// </param>
        /// <param name='keyName'>
        /// Required.
        /// </param>
        /// <param name='publisherId'>
        /// Required.
        /// </param>
        /// <param name='transport'>
        /// Optional.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        public async Task<HttpOperationResponse<string>> GetTokenWithOperationResponseAsync(string serviceNamespace, string eventHub, string keyName, string publisherId, string transport = null, CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // Validate
            if (serviceNamespace == null)
            {
                throw new ArgumentNullException("serviceNamespace");
            }
            if (eventHub == null)
            {
                throw new ArgumentNullException("eventHub");
            }
            if (keyName == null)
            {
                throw new ArgumentNullException("keyName");
            }
            if (publisherId == null)
            {
                throw new ArgumentNullException("publisherId");
            }
            
            // Tracing
            bool shouldTrace = ServiceClientTracing.IsEnabled;
            string invocationId = null;
            if (shouldTrace)
            {
                invocationId = ServiceClientTracing.NextInvocationId.ToString();
                Dictionary<string, object> tracingParameters = new Dictionary<string, object>();
                tracingParameters.Add("serviceNamespace", serviceNamespace);
                tracingParameters.Add("eventHub", eventHub);
                tracingParameters.Add("keyName", keyName);
                tracingParameters.Add("publisherId", publisherId);
                tracingParameters.Add("transport", transport);
                ServiceClientTracing.Enter(invocationId, this, "GetTokenAsync", tracingParameters);
            }
            
            // Construct URL
            string url = "";
            url = url + "/api/v1/sastoken/";
            url = url + Uri.EscapeDataString(serviceNamespace);
            url = url + "/";
            url = url + Uri.EscapeDataString(eventHub);
            url = url + "/";
            url = url + Uri.EscapeDataString(keyName);
            url = url + "/";
            url = url + Uri.EscapeDataString(publisherId);
            List<string> queryParameters = new List<string>();
            if (transport != null)
            {
                queryParameters.Add("transport=" + Uri.EscapeDataString(transport));
            }
            if (queryParameters.Count > 0)
            {
                url = url + "?" + string.Join("&", queryParameters);
            }
            string baseUrl = this.Client.BaseUri.AbsoluteUri;
            // Trim '/' character from the end of baseUrl and beginning of url.
            if (baseUrl[baseUrl.Length - 1] == '/')
            {
                baseUrl = baseUrl.Substring(0, baseUrl.Length - 1);
            }
            if (url[0] == '/')
            {
                url = url.Substring(1);
            }
            url = baseUrl + "/" + url;
            url = url.Replace(" ", "%20");
            
            // Create HTTP transport objects
            HttpRequestMessage httpRequest = new HttpRequestMessage();
            httpRequest.Method = HttpMethod.Get;
            httpRequest.RequestUri = new Uri(url);
            
            // Set Credentials
            if (this.Client.Credentials != null)
            {
                cancellationToken.ThrowIfCancellationRequested();
                await this.Client.Credentials.ProcessHttpRequestAsync(httpRequest, cancellationToken).ConfigureAwait(false);
            }
            
            // Send Request
            if (shouldTrace)
            {
                ServiceClientTracing.SendRequest(invocationId, httpRequest);
            }
            cancellationToken.ThrowIfCancellationRequested();
            HttpResponseMessage httpResponse = await this.Client.HttpClient.SendAsync(httpRequest, cancellationToken).ConfigureAwait(false);
            if (shouldTrace)
            {
                ServiceClientTracing.ReceiveResponse(invocationId, httpResponse);
            }
            HttpStatusCode statusCode = httpResponse.StatusCode;
            cancellationToken.ThrowIfCancellationRequested();
            string responseContent = await httpResponse.Content.ReadAsStringAsync().ConfigureAwait(false);
            if (statusCode != HttpStatusCode.OK)
            {
                HttpOperationException<object> ex = new HttpOperationException<object>();
                ex.Request = httpRequest;
                ex.Response = httpResponse;
                ex.Body = null;
                if (shouldTrace)
                {
                    ServiceClientTracing.Error(invocationId, ex);
                }
                throw ex;
            }
            
            // Create Result
            HttpOperationResponse<string> result = new HttpOperationResponse<string>();
            result.Request = httpRequest;
            result.Response = httpResponse;
            
            // Deserialize Response
            if (statusCode == HttpStatusCode.OK)
            {
                string resultModel = default(string);
                JToken responseDoc = null;
                if (string.IsNullOrEmpty(responseContent) == false)
                {
                    responseDoc = JToken.Parse(responseContent);
                }
                if (responseDoc != null)
                {
                    resultModel = responseDoc.ToString(Newtonsoft.Json.Formatting.Indented);
                }
                result.Body = resultModel;
            }
            
            if (shouldTrace)
            {
                ServiceClientTracing.Exit(invocationId, result);
            }
            return result;
        }
    }
}
